model: 'sbd'
network: 'ro_34'
task: 'snake'
resume: false
gpus: (0,1,2,3)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (60, 100, 130, 155, 180)
    gamma: 0.5
    batch_size: 40
    dataset: 'SbdTrain'
    num_workers: 12
    epoch: 200
test:
    dataset: 'SbdMini'
    batch_size: 1

heads: {'ct_hm': 20, 'wh': 256, 'mask': 1}
segm_or_bbox: 'segm'
